# Generated by Django 3.2.3 on 2021-06-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[(1, 'gminny'), (2, 'powiatowy'), (3, 'wojewódzki'), (4, 'krajowy'), (5, 'prywatny'), (6, 'inny')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[(1, 'brak współpracy'), (2, 'niska'), (3, 'średnia'), (4, 'wysoka')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(choices=[(1, 'niski'), (2, 'średni'), (3, 'wysoki'), (4, 'brak')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=128, unique=True)),
                ('investor_adress', models.CharField(max_length=128, unique=True)),
                ('investor_administration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.administrationlevel')),
                ('investor_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=128, unique=True)),
                ('designer_adress', models.CharField(max_length=128, unique=True)),
                ('designer_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.TextField(unique=True)),
                ('tender_date', models.DateTimeField()),
                ('estimated_value', models.FloatField(null=True)),
                ('deposit', models.FloatField(null=True)),
                ('administration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.administrationlevel')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.designer')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.investor')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.priority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.status')),
            ],
        ),
    ]
