# Generated by Django 3.2.3 on 2021-09-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[(1, 'gminny'), (2, 'powiatowy'), (3, 'wojewódzki'), (4, 'krajowy'), (5, 'prywatny'), (6, 'inny')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=128, unique=True)),
                ('designer_address', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=128, unique=True)),
                ('investor_address', models.CharField(max_length=256, unique=True)),
                ('investor_administration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.administrationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[(1, 'brak współpracy'), (2, 'niska'), (3, 'średnia'), (4, 'wysoka')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(choices=[(1, 'niski'), (2, 'średni'), (3, 'wysoki'), (4, 'brak')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[(1, 'brak startu'), (2, 'w przygotowaniu'), (3, 'rezygnacja'), (4, 'unieważniony'), (5, 'wygrany'), (6, 'przegrany')], default='brak startu', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.TextField(null=True, unique=True)),
                ('project_name', models.TextField(unique=True)),
                ('tender_date', models.DateField()),
                ('tender_time', models.TimeField(default=None, null=True)),
                ('open_time', models.TimeField(default=None, null=True)),
                ('deposit', models.FloatField(null=True)),
                ('announcement_number', models.TextField(default=None, null=True, unique=True)),
                ('announcement_date', models.DateField(default=None, null=True, unique=True)),
                ('voivodeship', models.TextField(choices=[(1, 'dolnośląskie'), (2, 'opolskie'), (3, 'wielkopolskie'), (4, 'lubuskie'), (5, 'śląskie'), (6, 'zachodniopomorskie'), (7, 'pomorskie'), (8, 'kujawsko-pomorskie'), (9, 'warmińsko-mazurskie'), (10, 'mazowieckie'), (11, 'łódzkie'), (12, 'świętokrzyskie'), (13, 'małopolskie'), (14, 'podkarpackie'), (15, 'lubelskie'), (16, 'podlaskie')], default=None, null=True)),
                ('estimated_value', models.FloatField(null=True)),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.designer')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.investor')),
                ('person', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.priority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.status')),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note'),
        ),
        migrations.AddField(
            model_name='designer',
            name='designer_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note'),
        ),
    ]
