# Generated by Django 3.2.3 on 2021-09-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[(1, 'gminny'), (2, 'powiatowy'), (3, 'wojewódzki'), (4, 'krajowy'), (5, 'prywatny'), (6, 'inny')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64, unique=True)),
                ('company_address', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=64, unique=True)),
                ('criteria_value', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=128, unique=True)),
                ('designer_address', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(choices=[(1, 'nieokreślono'), (2, 'Wrocław')], max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField(choices=[(1, 12), (2, 24), (3, 36), (4, 37), (5, 38), (6, 39), (7, 40), (8, 41), (9, 42), (10, 43), (11, 44), (12, 45), (13, 46), (14, 47), (15, 48), (16, 49), (17, 50), (18, 51), (19, 52), (20, 53), (20, 54), (21, 55), (22, 56), (23, 57), (24, 58), (25, 59), (26, 60), (27, 61), (28, 62), (29, 63), (30, 64), (31, 65), (32, 66), (33, 67), (34, 68), (35, 69), (36, 70), (37, 71), (38, 72), (39, 73), (39, 74), (40, 75), (41, 76), (42, 77), (43, 78), (44, 79), (45, 80), (46, 81), (47, 82), (48, 83), (49, 84), (50, 85), (51, 86), (52, 87), (53, 88), (54, 89), (55, 90), (56, 91), (57, 92), (58, 93), (59, 94), (60, 95), (61, 96), (62, 97), (63, 98), (64, 99), (65, 100), (66, 101), (67, 102), (68, 103), (69, 104), (70, 105), (71, 106), (72, 107), (73, 108), (74, 109), (75, 110), (76, 111), (77, 112), (78, 113), (79, 114), (80, 115), (81, 116), (82, 117), (83, 118), (84, 119), (85, 120)], default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=128, unique=True)),
                ('investor_address', models.CharField(max_length=256, unique=True)),
                ('investor_administration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.administrationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[(1, 'brak współpracy'), (2, 'niska'), (3, 'średnia'), (4, 'wysoka')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(choices=[(1, 'nieokreślono'), (2, 'ryczałt'), (3, 'polski ryczałt'), (4, 'ilościowe'), (5, 'inne')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(choices=[(1, 'brak'), (2, 'niski'), (3, 'średni'), (4, 'wysoki')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[(1, 'brak startu'), (2, 'w przygotowaniu'), (3, 'rezygnacja'), (4, 'unieważniony'), (5, 'wygrany'), (6, 'przegrany')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship_name', models.CharField(choices=[(1, 'nieokreślono'), (2, 'dolnośląskie'), (3, 'opolskie'), (4, 'wielkopolskie'), (5, 'lubuskie'), (6, 'śląskie'), (7, 'zachodniopomorskie'), (8, 'pomorskie'), (9, 'kujawsko-pomorskie'), (10, 'warmińsko-mazurskie'), (11, 'mazowieckie'), (12, 'łódzkie'), (13, 'świętokrzyskie'), (14, 'małopolskie'), (15, 'podkarpackie'), (16, 'lubelskie'), (17, 'podlaskie')], max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_value', models.FloatField(default=None, null=True)),
                ('offer_deadline', models.DateField(default=None, null=True)),
                ('offer_guarantee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.guarantee')),
                ('other_criteria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.criteria')),
                ('tenderer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_budget', models.FloatField(default=None, null=True)),
                ('tenderers', models.ManyToManyField(default=None, to='dyplomowa_app.Tenderer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.TextField(default=None, max_length=32, null=True, unique=True)),
                ('tender_time', models.TimeField(default=None, null=True)),
                ('open_time', models.TimeField(default=None, null=True)),
                ('deposit', models.FloatField(default=None, null=True)),
                ('announcement_number', models.TextField(default=None, null=True)),
                ('announcement_date', models.DateField(default=None, null=True)),
                ('tender_date', models.DateField(default=None, null=True)),
                ('project_name', models.TextField(max_length=512, unique=True)),
                ('estimated_value', models.FloatField(default=None, null=True)),
                ('project_deadline', models.DateField(default=None, null=True)),
                ('mma_quantity', models.IntegerField(default=None, null=True)),
                ('project_url', models.URLField(default=None, null=True, unique=True)),
                ('rc_date', models.DateField(default=None, null=True)),
                ('rc_agree', models.BooleanField(default=None, null=True)),
                ('evaluation_criteria', models.TextField(default=None, null=True)),
                ('payment_criteria', models.TextField(default=None, null=True)),
                ('remarks', models.TextField(default=None, null=True)),
                ('designer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.designer')),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.division')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.investor')),
                ('jv_partners', models.ManyToManyField(default=None, to='dyplomowa_app.Company')),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.paymentmethod')),
                ('person', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.priority')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.status')),
                ('tender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.tender')),
                ('voivodeship', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.voivodeship')),
            ],
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note'),
        ),
        migrations.AddField(
            model_name='designer',
            name='designer_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note'),
        ),
    ]
