# Generated by Django 3.2.3 on 2021-10-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderer',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
