# Generated by Django 3.2.3 on 2021-10-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='months',
            new_name='month',
        ),
    ]
