# Generated by Django 3.2.3 on 2021-10-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='division',
            field=models.ManyToManyField(to='dyplomowa_app.Division'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='division',
            field=models.ManyToManyField(to='dyplomowa_app.Division'),
        ),
        migrations.AddField(
            model_name='designer',
            name='division',
            field=models.ManyToManyField(to='dyplomowa_app.Division'),
        ),
        migrations.AddField(
            model_name='investor',
            name='division',
            field=models.ManyToManyField(to='dyplomowa_app.Division'),
        ),
    ]
