# Generated by Django 3.2.3 on 2021-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_note',
            field=models.FloatField(default=None, max_length=4, null=True),
        ),
    ]
