# Generated by Django 3.2.3 on 2021-09-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='division_creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
