# Generated by Django 3.2.3 on 2021-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tender_date',
            new_name='tender_date_date',
        ),
        migrations.AddField(
            model_name='project',
            name='tender_date_days',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tender_date_months',
            field=models.DateField(default=None, null=True),
        ),
    ]
