# Generated by Django 3.2.3 on 2021-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria_name',
            field=models.CharField(max_length=64),
        ),
    ]
