# Generated by Django 3.2.3 on 2021-09-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.TextField(max_length=32, null=True, unique=True),
        ),
    ]
