# Generated by Django 3.2.3 on 2021-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderer',
            name='other_criteria',
        ),
        migrations.AddField(
            model_name='tenderer',
            name='other_criteria',
            field=models.ManyToManyField(default=None, to='dyplomowa_app.Criteria'),
        ),
    ]
