# Generated by Django 3.2.3 on 2021-06-13 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(unique=True)),
                ('tender_date', models.DateTimeField()),
                ('estimated_value', models.FloatField(null=True)),
                ('deposit', models.FloatField(null=True)),
                ('administration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.administrationlevel')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.designer')),
            ],
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_adress',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.AddField(
            model_name='project',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.investor'),
        ),
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.priority'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.status'),
        ),
    ]
