# Generated by Django 3.2.3 on 2021-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0002_rename_months_month_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='is_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='is_guarantee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='is_other_criteria',
            field=models.BooleanField(default=False),
        ),
    ]
