# Generated by Django 3.2.3 on 2021-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0002_auto_20210613_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tender_date',
            field=models.DateField(),
        ),
    ]
