# Generated by Django 3.2.3 on 2021-09-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0002_auto_20210905_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(choices=[(1, 'nieokreślono'), (2, 'Wrocław')], max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(choices=[(1, 'nieokreślono'), (2, 'ryczałt'), (3, 'polski ryczałt'), (4, 'ilościowe'), (5, 'inne')], max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='mma_quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rc_agree',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rc_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[(1, 'brak startu'), (2, 'w przygotowaniu'), (3, 'rezygnacja'), (4, 'unieważniony'), (5, 'wygrany'), (6, 'przegrany')], max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.division'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.paymentmethod'),
        ),
    ]
