# Generated by Django 3.2.3 on 2021-09-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0002_auto_20210911_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
