# Generated by Django 3.2.3 on 2021-10-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0002_alter_criteria_criteria_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria_name',
            field=models.CharField(max_length=128),
        ),
    ]
