# Generated by Django 3.2.3 on 2021-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0002_auto_20210925_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_deadline',
            new_name='project_deadline_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tender_date_date',
            new_name='tender_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tender_date_days',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tender_date_months',
        ),
        migrations.AddField(
            model_name='project',
            name='project_deadline_days',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_deadline_months',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
