# Generated by Django 3.2.3 on 2021-10-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0003_alter_criteria_criteria_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderer',
            name='tenderer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.company'),
        ),
    ]
