# Generated by Django 3.2.3 on 2021-09-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0003_auto_20210911_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship_name', models.CharField(choices=[(1, 'nieokreślono'), (2, 'dolnośląskie'), (3, 'opolskie'), (4, 'wielkopolskie'), (5, 'lubuskie'), (6, 'śląskie'), (7, 'zachodniopomorskie'), (8, 'pomorskie'), (9, 'kujawsko-pomorskie'), (10, 'warmińsko-mazurskie'), (11, 'mazowieckie'), (12, 'łódzkie'), (13, 'świętokrzyskie'), (14, 'małopolskie'), (15, 'podkarpackie'), (16, 'lubelskie'), (17, 'podlaskie')], max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_criteria',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='investor_budget',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='join_venture_memmers',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_criteria',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='voivodeship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.voivodeship'),
        ),
    ]
