# Generated by Django 3.2.3 on 2021-06-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0003_alter_project_tender_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='administration_level',
        ),
    ]
