# Generated by Django 3.2.3 on 2021-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poviat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poviat_name', models.CharField(choices=[], max_length=64, unique=True)),
            ],
        ),
    ]
