# Generated by Django 3.2.3 on 2021-09-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0003_alter_investor_investor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='designer_note',
        ),
        migrations.AddField(
            model_name='designer',
            name='designer_note',
            field=models.FloatField(default=None, max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='DesignerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_note_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.investor')),
                ('designer_note_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note')),
                ('designer_note_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
