# Generated by Django 3.2.3 on 2021-11-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0003_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_administration_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowa_app.administrationlevel'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_poviat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowa_app.poviat'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_voivodeship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowa_app.voivodeship'),
        ),
        migrations.AlterField(
            model_name='investornote',
            name='investor_note_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
