# Generated by Django 3.2.3 on 2021-10-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0004_alter_tenderer_tenderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderer',
            name='tenderer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.company'),
        ),
    ]
