# Generated by Django 3.2.3 on 2021-09-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0004_auto_20210930_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designernote',
            old_name='designer_note_investor',
            new_name='designer_note_designer',
        ),
    ]
