# Generated by Django 3.2.3 on 2021-09-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0004_poviat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poviat',
        ),
    ]
