# Generated by Django 3.2.3 on 2021-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0004_auto_20210926_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tender_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tender_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
