# Generated by Django 3.2.3 on 2021-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0004_remove_project_administration_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[(1, 'brak startu'), (2, 'w przygotowaniu'), (3, 'rezygnacja'), (4, 'unieważniony'), (5, 'wygrany'), (6, 'przegrany')], default='brak startu', max_length=32, unique=True),
        ),
    ]
