# Generated by Django 3.2.3 on 2021-09-11 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0004_auto_20210911_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='JV_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jv_member_name', models.CharField(max_length=64, unique=True)),
                ('jv_member_address', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='join_venture_memmers',
        ),
        migrations.AddField(
            model_name='project',
            name='project_deadline',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='announcement_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='announcement_number',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deposit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_value',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='person',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.TextField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tender_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='jv_members',
            field=models.ManyToManyField(default=None, null=True, to='dyplomowa_app.JV_Member'),
        ),
    ]
