# Generated by Django 3.2.3 on 2021-09-11 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0005_auto_20210911_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jv_members',
            field=models.ManyToManyField(default=None, to='dyplomowa_app.JV_Member'),
        ),
        migrations.AlterField(
            model_name='project',
            name='person',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
