# Generated by Django 3.2.3 on 2021-09-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0005_rename_designer_note_investor_designernote_designer_note_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designernote',
            name='designer_note_designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.designer'),
        ),
    ]
