# Generated by Django 3.2.3 on 2021-06-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0005_status_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='designer_adress',
            new_name='designer_address',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='investor_adress',
            new_name='investor_address',
        ),
    ]
