# Generated by Django 3.2.3 on 2021-09-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0006_auto_20210926_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.priority'),
        ),
    ]
