# Generated by Django 3.2.3 on 2021-06-13 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0006_auto_20210613_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='person',
        ),
        migrations.AddField(
            model_name='project',
            name='person',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
