# Generated by Django 3.2.3 on 2021-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0006_auto_20210911_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JV_Member',
            new_name='JV_Partner',
        ),
        migrations.RenameField(
            model_name='jv_partner',
            old_name='jv_member_address',
            new_name='jv_partner_address',
        ),
        migrations.RenameField(
            model_name='jv_partner',
            old_name='jv_member_name',
            new_name='jv_partner_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='jv_members',
        ),
        migrations.AddField(
            model_name='project',
            name='jv_partners',
            field=models.ManyToManyField(default=None, to='dyplomowa_app.JV_Partner'),
        ),
    ]
