# Generated by Django 3.2.3 on 2021-10-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0006_alter_designernote_designer_note_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tender',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.tender'),
        ),
    ]
