# Generated by Django 3.2.3 on 2021-09-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0007_auto_20210915_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_poviat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.poviat'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_voivodeship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.voivodeship'),
        ),
        migrations.AddField(
            model_name='designer',
            name='designer_poviat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.poviat'),
        ),
        migrations.AddField(
            model_name='designer',
            name='designer_voivodeship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.voivodeship'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_poviat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.poviat'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_voivodeship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.voivodeship'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='designer_note',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.note'),
        ),
    ]
