# Generated by Django 3.2.3 on 2021-10-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0007_alter_project_tender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='tenderers',
            new_name='tenderer',
        ),
    ]
