# Generated by Django 3.2.3 on 2021-09-05 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0007_auto_20210613_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tender_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
