# Generated by Django 3.2.3 on 2021-12-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0008_auto_20211206_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
    ]
