# Generated by Django 3.2.3 on 2021-09-18 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dyplomowa_app', '0008_auto_20210916_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='division_person',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
