# Generated by Django 3.2.3 on 2021-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0009_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[(1, 'brak startu'), (2, 'w przygotowaniu'), (3, 'rezygnacja'), (4, 'unieważniony'), (5, 'wygrany'), (6, 'przegrany'), (7, 'wykluczenie')], max_length=32, unique=True),
        ),
    ]
