# Generated by Django 3.2.3 on 2021-09-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0009_division_division_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyplomowa_app.division'),
        ),
    ]
