# Generated by Django 3.2.3 on 2022-08-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0011_auto_20220318_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='designer_phone',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
