# Generated by Django 3.2.3 on 2022-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0012_designer_designer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investor_email',
            field=models.EmailField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_phone',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
