# Generated by Django 3.2.3 on 2022-08-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0013_auto_20220818_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_contact',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
