# Generated by Django 3.2.3 on 2022-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0014_auto_20220819_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_subcontractor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
