# Generated by Django 3.2.3 on 2022-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0015_company_is_subcontractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.TextField(default=None, null=True),
        ),
    ]
