# Generated by Django 3.2.3 on 2022-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowa_app', '0016_company_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branch',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
